//récolter les ingrédients dans le tableau de recettes

//résultat des ingrédients récoltés dans recipes[]
export const ingredientsArray = [
    "Lait de coco",
    "Jus de citron",
    "Crème de coco",
    "Sucre",
    "Glaçons",
    "Thon rouge",
    "Concombre",
    "Tomate",
    "Carotte",
    "Citron Vert",
    "Poulet",
    "Coulis de tomate",
    "Oignon",
    "Poivron rouge",
    "Huile d'olive",
    "Riz blanc",
    "Thon en miettes",
    "Oeuf dur",
    "Maïs",
    "Vinaigrette",
    "Pâte feuilletée",
    "Crème fraiche",
    "Gruyère râpé",
    "Moutarde de Dijon",
    "Pomme",
    "Oeuf",
    "Sucre en poudre",
    "Chocolat au lait",
    "Crème liquide",
    "Beurre",
]